export const getCountryName = (code: string) => {
    const map: Record<string, string> = {
      US: "United States",
      MX: "Mexico",
      BR: "Brazil",
      GB: "United Kingdom",
      DE: "Germany",
      FR: "France",
      CA: "Canada",
      IN: "India",
      ES: "Spain",
      IT: "Italy",
      CN: "China",
      JP: "Japan",
      KR: "South Korea",
      RU: "Russia",
      AU: "Australia",
      AR: "Argentina",
      CL: "Chile",
      CO: "Colombia",
      PE: "Peru",
      VE: "Venezuela",
      ZA: "South Africa",
      EG: "Egypt",
      NG: "Nigeria",
      KE: "Kenya",
      GH: "Ghana",
      PT: "Portugal",
      SE: "Sweden",
      NO: "Norway",
      FI: "Finland",
      DK: "Denmark",
      NL: "Netherlands",
      BE: "Belgium",
      CH: "Switzerland",
      AT: "Austria",
      IE: "Ireland",
      PL: "Poland",
      CZ: "Czech Republic",
      SK: "Slovakia",
      HU: "Hungary",
      RO: "Romania",
      BG: "Bulgaria",
      GR: "Greece",
      TR: "Turkey",
      IL: "Israel",
      SA: "Saudi Arabia",
      AE: "United Arab Emirates",
      QA: "Qatar",
      KW: "Kuwait",
      BH: "Bahrain",
      JO: "Jordan",
      MA: "Morocco",
      DZ: "Algeria",
      TN: "Tunisia",
      ET: "Ethiopia",
      UG: "Uganda",
      SD: "Sudan",
      PK: "Pakistan",
      BD: "Bangladesh",
      LK: "Sri Lanka",
      TH: "Thailand",
      VN: "Vietnam",
      MY: "Malaysia",
      SG: "Singapore",
      ID: "Indonesia",
      PH: "Philippines",
      NZ: "New Zealand",
      UA: "Ukraine",
      RS: "Serbia",
      HR: "Croatia",
      SI: "Slovenia",
      BA: "Bosnia and Herzegovina",
      AL: "Albania",
      MK: "North Macedonia",
      GE: "Georgia",
      AM: "Armenia",
      KZ: "Kazakhstan",
      UZ: "Uzbekistan",
      IR: "Iran",
      IQ: "Iraq",
      SY: "Syria",
      AF: "Afghanistan",
      NP: "Nepal",
      MM: "Myanmar",
      KH: "Cambodia",
      LA: "Laos",
      TW: "Taiwan",
      HK: "Hong Kong",
      MO: "Macau",
      TT: "Trinidad and Tobago",
      JM: "Jamaica",
      DO: "Dominican Republic",
      HN: "Honduras",
      SV: "El Salvador",
      GT: "Guatemala",
      CR: "Costa Rica",
      PA: "Panama",
      NI: "Nicaragua",
      PY: "Paraguay",
      UY: "Uruguay",
      BO: "Bolivia",
      EC: "Ecuador",
      CU: "Cuba",
      PR: "Puerto Rico",
      // TT: "Trinidad and Tobago",
      LU: "Luxembourg",
      LI: "Liechtenstein",
      IS: "Iceland",
      EE: "Estonia",
      LV: "Latvia",
      LT: "Lithuania",
      CY: "Cyprus",
      MT: "Malta",
      AZ: "Azerbaijan",
      OM: "Oman",
      YE: "Yemen",
      ZW: "Zimbabwe",
      ZM: "Zambia",
      MZ: "Mozambique",
      BW: "Botswana",
      NA: "Namibia",
      AO: "Angola",
      CM: "Cameroon",
      CI: "Ivory Coast",
      SN: "Senegal",
      BF: "Burkina Faso",
      ML: "Mali",
      TG: "Togo",
      BJ: "Benin",
      GA: "Gabon",
      CG: "Congo",
      CD: "Democratic Republic of the Congo",
      GM: "Gambia",
      GN: "Guinea",
      GQ: "Equatorial Guinea",
      MG: "Madagascar",
      MU: "Mauritius",
      SC: "Seychelles",
      FJ: "Fiji",
      PG: "Papua New Guinea",
      SB: "Solomon Islands",
      WS: "Samoa",
      TO: "Tonga",
      VU: "Vanuatu",
      MH: "Marshall Islands",
      FM: "Micronesia",
      KI: "Kiribati"
    };
    
    return map[code.toUpperCase()] || code;
  };